config/routes.rb
Cleaner::Application.routes.draw do
  root to: 'cleaner#index'
  post 'cleaner/assign'
  post 'cleaner/init'

  resources :users, only: [:new, :create, :index] do
    post :seated_change
  end
end

app/models/user.rb
# -*- coding: utf-8 -*-
class User < ActiveRecord::Base
  attr_accessible :name, :throw_date, :vacuum_up_date, :wiping_date, :seated, :throw_status, :vacuum_up_status, :wiping_status

  scope :recent_no_worker, proc {
    this_week_beginning_day = Date.today.at_beginning_of_week - 1
    where('vacuum_up_date < ? AND wiping_date < ? AND throw_date < ?', this_week_beginning_day, this_week_beginning_day, this_week_beginning_day)
  }

  scope :thrower_target, proc {
    where(:seated => true).where(:throw_status => 'todo').recent_no_worker.order('throw_date ASC')
  }
  scope :vacuumer_target, proc {
    where(:seated => true).where(:vacuum_up_status => 'todo').recent_no_worker.order('vacuum_up_date ASC')
  }
  scope :wipingner_target, proc {
    where(:seated => true).where(:wiping_status => 'todo').recent_no_worker.order('wiping_date ASC')
  }

  # 週1回だけ呼ぶよ
  def self.rehash_cleaners
    self.cleaners_done
    next_throwers =  User.thrower_target
    next_vacuumers = User.vacuumer_target
    next_wipingers = User.wipingner_target

    if (next_throwers.size < 2) && (next_vacuumers.size < 2) && (next_wipingers.size < 2)
      self.all_cleaners_todo
    end

    self.cleaners_doing
  end

  # 今週の掃除当番を選択
  def self.cleaners_doing
    self.thrower_target.limit(2).each do |user|
      user.throw_status = 'doing'
      user.throw_date = Date.today.at_beginning_of_week
      user.save
    end

    self.vacuumer_target.limit(2).each do |user|
      user.vacuum_up_status = 'doing'
      user.vacuum_up_date = Date.today.at_beginning_of_week
      user.save
    end

    self.wipingner_target.limit(2).each do |user|
      user.wiping_status = 'doing'
      user.wiping_date = Date.today.at_beginning_of_week
      user.save
    end
  end

  # 今週の掃除当番から開放
  def self.cleaners_done
    User.where(:throw_status => 'doing').each do |user|
      user.throw_status = 'done'
      user.save
    end

    User.where(:vacuum_up_status => 'doing').each do |user|
      user.vacuum_up_status = 'done'
      user.save
    end

    User.where(:wiping_status => 'doing').each do |user|
      user.wiping_status = 'done'
      user.save
    end
  end

  # 割り当てれる人がいなかった時
  def self.all_cleaners_todo
    User.all.each do |user|
      user.throw_status =     'todo'
      user.vacuum_up_status = 'todo'
      user.wiping_status =    'todo'
      user.save
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  http_basic_authenticate_with :name => ENV["BASIC_AUTH_NAME"], :password => ENV["BASIC_AUTH_PASSWORD"] if Rails.env.production?
end

app/controllers/cleaner_controller.rb
class CleanerController < ApplicationController
  def index
    @thowers   = User.where(:throw_status =>     'doing')
    @vacuumers = User.where(:vacuum_up_status => 'doing')
    @wipingers = User.where(:wiping_status =>    'doing')
    @users = User.all
  end

  def assign
    User.rehash_cleaners
    redirect_to root_path
  end

  def init
    load "#{Rails.root}/db/seeds.rb"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to root_path, notice: '新規登録したった'
    else
      render 'users/new'
    end
  end

  def seated_change
    @user = User.find(params[:user_id])
    @user.seated = !@user.seated
    @user.save
    redirect_to :users
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @thowers   = User.where(:throw_status =>     'doing')
    @vacuumers = User.where(:vacuum_up_status => 'doing')
    @wipingers = User.where(:wiping_status =>    'doing')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cleaners_helper.rb
# -*- coding: utf-8 -*-
module CleanersHelper
  def mailto()
    "mailto:sp@esm.co.jp?subject=#{mail_subject}&amp;body=#{mail_body}"
  end

  private
  def mail_subject
    "【掃除当番連絡】10月10日〜10月15日"
  end

  private
  def mail_body
<<-EOD
* テーブル拭き
#{@wipingers.map(&:name).join(', ')}
期間中3回を目安に（月・水・金など）できるだけ朝お願いします

* ゴミ捨て
#{@thowers.map(&:name).join(', ')}
期間中2回を目安に（火・木など）

* 掃除機
#{@vacuumers.map(&:name).join(', ')}
期間中1回(9時前または18時30分以降)
EOD
  end
end

app/helpers/users_helper.rb
# -*- coding: utf-8 -*-
module UsersHelper
  # TODO: i18n
  def status_to_message(status)
    case status
    when 'todo'
      "未実施"
    when 'doing'
      "今週!"
    when 'done'
      "実施済み"
    else
    end
  end
end

app/views/cleaner/index.html.haml
%h1 ESM Cleaner Beta
= flash[:notice]

%h2 ゴミほり
%ul
- @thowers.each do |user|
  %li= user.name

%h2 掃除機
%ul
- @vacuumers.each do |user|
  %li= user.name

%h2 テーブル拭き
%ul
- @wipingers.each do |user|
  %li= user.name

%div= link_to '新規東京支社配属者を登録', :new_user
%div= link_to '東京支社一覧', :users
%div= link_to 'メールを出す', mailto

- if Rails.env == 'development'
  %hr
  %h3 以下は開発時のみ表示されます
  %div= button_to 'Assign', :action => 'assign'
  %div= button_to 'Data Init', :action => 'init'

  %table
    %tr
      %th なまえ
      %th ごみほり
      %th そうじき
      %th てーぶるふき
    - @users.each do |user|
      %tr
        %td= user.name
        %td
          = user.throw_status
          = "(#{user.throw_date})"
        %td
          = user.vacuum_up_status
          = "(#{user.vacuum_up_date})"
        %td
          = user.wiping_status
          = "(#{user.wiping_date})"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cleaner</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/create.html.haml
%h1 Users#create
%p Find me in app/views/users/create.html.haml

app/views/users/index.html.haml
%h1 Hi Oshige, Hi Sumita
= link_to 'トップページに戻る', root_path

%table
  %tr
    %th 名前
    %th ゴミ捨て
    %th 掃除機
    %th テーブル拭き
    %th 支社にいる?
  - @users.each do |user|
    %tr
      %td= user.name
      %td= status_to_message(user.throw_status)
      %td= status_to_message(user.vacuum_up_status)
      %td= status_to_message(user.wiping_status)
      %td= button_to (user.seated ? '着席している' : '社外常駐'), user_seated_change_path(user)

app/views/users/new.html.haml
%h1 Hi Oshige

= form_for(@user) do |f|
  = f.text_field :name
  = f.submit


= link_to 'トップページに戻る', root_path